# SwiftLint configuration for HomeKit MCP Server

included:
  - HomeKitSync
  - HomeKitSyncTests

excluded:
  - Pods
  - DerivedData
  - Build

# Rule configuration
line_length:
  warning: 120
  error: 150

file_length:
  warning: 1450
  error: 1750

function_body_length:
  warning: 180
  error: 280

type_body_length:
  warning: 1400
  error: 1600

cyclomatic_complexity:
  warning: 30
  error: 40

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try

# Enabled opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

# Custom rules can be added here as needed